avtomat/urls.py
from django.conf.urls import url
from .views import AvtomatView, AvtomatAlphabetView, avtomat_form_view, street_json_view, StreetView, StreetCreateView, StreetEditView, CityView, CityCreateView, CityEditView, avtomat_json_view

urlpatterns = [
    url(r'^$', AvtomatView.as_view(), name='avtomat'),
    url(r'^(\w)/$', AvtomatAlphabetView.as_view(), name='avtomat_alphabet'),
    url(r'^avtomat_form/(?P<pk>\d+)/$', avtomat_form_view, name='avtomat_form'),
    url(r'^street_json/$', street_json_view, name='street_json'),
    url(r'^street/$', StreetView.as_view(), name='street'),
    url(r'^street_create/$', StreetCreateView.as_view(), name='street_create'),
    url(r'^street_edit/(?P<pk>\d+)/$', StreetEditView.as_view(), name='street_edit'),
    url(r'^city/$', CityView.as_view(), name='city'),
    url(r'^city_create/$', CityCreateView.as_view(), name='city_create'),
    url(r'^city_edit/(?P<pk>\d+)/$', CityEditView.as_view(), name='city_edit'),
    url(r'^avtomat_json/$', avtomat_json_view, name='avtomat_json'),
]

route/urls.py
from django.conf.urls import url
from .views import RouteView, RouteCreateView, RouteEditView, route_delete_view


urlpatterns = [
    url(r'^$', RouteView.as_view(), name='route'),
    url(r'^create/$', RouteCreateView.as_view(), name='route_create'),
    url(r'^edit/(?P<pk>\d+)/$', RouteEditView.as_view(), name='route_edit'),
    url(r'^delete/(?P<pk>\d+)', route_delete_view, name='route_delete'),
]

avtomat/models.py
# coding=utf-8
from __future__ import unicode_literals
from django.db import models
import googlemaps
from route.models import Route


class City(models.Model):
    city = models.CharField(max_length=20, unique=True, verbose_name='Город')

    def __unicode__(self):
        return self.city

    class Meta:
        db_table = 'city'
        verbose_name = 'Город'
        verbose_name_plural = 'Города'


class Street(models.Model):
    city = models.ForeignKey(City, verbose_name='Город')
    street = models.CharField(max_length=50, verbose_name='Улица')

    def __unicode__(self):
        return self.street

    class Meta:
        db_table = 'street'
        verbose_name = 'Улица'
        verbose_name_plural = 'Улицы'
        ordering = ['street', ]


class Avtomat(models.Model):

    SIZE_OF_AVTOMAT = (
        (470, u'Одинарный'),
        (940, u'Двойной'),
    )

    number = models.IntegerField(verbose_name='Номер автомата')
    street = models.ForeignKey(Street, blank=True, null=True, on_delete=models.SET_NULL, verbose_name='Улица')
    house = models.CharField(max_length=10, blank=True, null=True, verbose_name='Номер дома')
    latitude = models.FloatField(blank=True, null=True, verbose_name='Широта')
    longitude = models.FloatField(blank=True, null=True, verbose_name='Долгота')
    route = models.ForeignKey(Route, blank=True, null=True, on_delete=models.SET_NULL, verbose_name='Маршрут')
    water_price = models.IntegerField(blank=True, null=True, verbose_name='Цена за один литр')
    size = models.IntegerField(blank=True, null=True, choices=SIZE_OF_AVTOMAT, verbose_name='Обьем автомата')
    phone = models.CharField(max_length=12, blank=True, null=True, verbose_name='Телефон')
    register = models.IntegerField(blank=True, null=True, verbose_name='Номер регистратора')
    security = models.IntegerField(blank=True, null=True, verbose_name='Охранный обьект')
    competitors = models.BooleanField(default=False, verbose_name='Конкуренты')

    def __unicode__(self):
        if self.street:
            if self.street.city.city == 'Харьков':
                return '%s %s' % (self.street, self.house)
            else:
                return '%s %s(%s)' % (self.street, self.house, self.street.city)
        else:
            return 'Новый автомат %s' % self.number

#    def save(self, *args, **kwargs):
#        if self.street and self.house:
#            try:
#                api_key = 'AIzaSyB3wwrPtsRIyV2twvjKvHAwE-Q3aNx5Yjs'
#                address = u'%s, %s, %s' % (self.street.city, self.street, self.house)
#                gmap = googlemaps.Client(key=api_key)
#                geocode_result = gmap.geocode(address)
#                position = geocode_result[0]['geometry']['location']
#                self.latitude = position['lat']
#                self.longitude = position['lng']
#            except:
#                pass
#        super(Avtomat, self).save(*args, **kwargs)

    class Meta:
        ordering = ['street', '-house']
        db_table = 'avtomat'
        verbose_name = 'Автомат'
        verbose_name_plural = 'Автоматы'

avtomat/forms.py
# coding=utf-8
from .models import Avtomat, City
from django import forms


class UIWidget(forms.TextInput):
    class Media:
        css = {'all': ('//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css', )}
        js = ('https://code.jquery.com/ui/1.12.1/jquery-ui.js', )


class AvtomatForm(forms.ModelForm):

    city = forms.ModelChoiceField(queryset=City.objects.all(), label=u'Город')
    street_label = forms.CharField(widget=UIWidget, max_length=50, label=u'Улица')

    class Meta:
        model = Avtomat
        fields = ['city', 'street_label', 'street', 'house', 'route', 'water_price', 'size', 'phone', 'register', 'security', 'competitors']
        widgets = {'street': forms.HiddenInput}

avtomat/views.py
from django.shortcuts import render, redirect, reverse
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, CreateView, UpdateView
from .models import Avtomat, City, Street
from .forms import AvtomatForm


class AvtomatView(LoginRequiredMixin, ListView):
    queryset = Avtomat.objects.all().select_related('route', 'street__city')
    template_name = 'avtomat/avtomat.html'
    context_object_name = 'avtomat_table'


class AvtomatAlphabetView(LoginRequiredMixin, ListView):
    template_name = 'avtomat/avtomat.html'
    context_object_name = 'avtomat_table'

    def get_queryset(self):
        return Avtomat.objects.filter(street__street__istartswith=self.args[0]).select_related('route', 'street__city')


@login_required
def avtomat_form_view(request, pk):
    avtomat = Avtomat.objects.get(pk=pk)
    if request.method == 'POST':
        form = AvtomatForm(request.POST)
        if form.is_valid():
            form = AvtomatForm(request.POST, instance=avtomat)
            form.save()
#            if not avtomat.latitude or not avtomat.longitude:
#                return redirect('/avtomat/' + '?number=%s' % avtomat.number)
#            else:
	    return redirect('avtomat')
    else:
        try:
            city = avtomat.street.city
        except AttributeError:
            city = u''
        try:
            street_label = avtomat.street.street
        except AttributeError:
            street_label = u''
        form = AvtomatForm(instance=avtomat, initial={'city': city, 'street_label': street_label})
        return render(request, 'avtomat/avtomat_form.html', {'form': form, 'avtomat': avtomat})


@login_required
def street_json_view(request):
    term = request.GET['term'].capitalize()
    city = request.GET['city']
    data = Street.objects.filter(city=city, street__startswith=term)
    streets = []
    for street in data:
        street = {'id': street.id, 'label': street.street}
        streets.append(street)
    return JsonResponse(streets, safe=False)


class StreetView(LoginRequiredMixin, ListView):
    queryset = Street.objects.all().select_related('city')
    template_name = 'avtomat/street.html'
    context_object_name = 'street_table'


class StreetCreateView(LoginRequiredMixin, CreateView):
    model = Street
    fields = ['city', 'street']
    template_name = 'avtomat/street_create.html'

    def get_success_url(self):
        return reverse('street')


class StreetEditView(LoginRequiredMixin, UpdateView):
    model = Street
    fields = ['city', 'street']
    template_name = 'avtomat/street_edit.html'

    def get_success_url(self):
        return reverse('street')


class CityView(LoginRequiredMixin, ListView):
    model = City
    template_name = 'avtomat/city.html'
    context_object_name = 'city_table'


class CityCreateView(LoginRequiredMixin, CreateView):
    model = City
    fields = ['city', ]
    template_name = 'avtomat/city_create.html'

    def get_success_url(self):
        return reverse('city')


class CityEditView(LoginRequiredMixin, UpdateView):
    model = City
    fields = ['city', ]
    template_name = 'avtomat/city_edit.html'

    def get_success_url(self):
        return reverse('city')


@login_required
def avtomat_json_view(request):
    term = request.GET.get('term').capitalize()
    data = Avtomat.objects.filter(street__street__startswith=term)
    avtomats = []
    for avtomat in data:
        avtomat = {'label': str(avtomat), 'id': avtomat.id}
        avtomats.append(avtomat)
    return JsonResponse(avtomats, safe=False)

templates/avtomat/avtomat.html
{% extends 'base.html' %}
{% load extras %}

{% block title %}Список автоматов{% endblock %}

{% block content %}

    <ul class="nav nav-tabs">
        <li role="presentation" class="active"><a href="{% url 'avtomat' %}">Автоматы</a></li>
        <li role="presentation"><a href="{% url 'route' %}">Маршруты</a></li>
        <li role="presentation"><a href="{% url 'street' %}">Улицы</a></li>
        <li role="presentation"><a href="{% url 'city' %}">Города</a></li>
    </ul>
    <br>

    {% block alphabet %}
        {% include 'alphabet.html' %}
    {% endblock %}

    <h3>Список автоматов</h3>
    <table class="table tablesorter">
    <thead>
        <tr class="info">
            <th></th>
            <th>Номер</th>
            <th>Город</th>
            <th>Адрес</th>
            <th>Маршрут</th>
            <th>Цена</th>
            <th>Обьем</th>
            <th>Телефон</th>
            <th>Регистратор</th>
            <th>Охрана</th>
            <th>Конкуренты</th>
        </tr>
    </thead>
    <tbody>
    {% for avtomat in avtomat_table %}
        <tr>
            <td><a href="{% url 'avtomat_form' avtomat.pk %}">Ред</a></td>
            <td>{{ avtomat.number }}</td>
            <td>{{ avtomat.street.city }}</td>
            <td>{{ avtomat }}</td>
            <td>{% if avtomat.route %}{{ avtomat.route }}{% else %}-{% endif %}</td>
            <td>{% if avtomat.water_price %}{{ avtomat.water_price }}{% else %}-{% endif %}</td>
            <td>{% if avtomat.size %}{{ avtomat.size }}{% else %}-{% endif %}</td>
            <td>{% if avtomat.phone %}{{ avtomat.phone }}{% else %}-{% endif %}</td>
            <td>{% if avtomat.register %}{{ avtomat.register }}{% else %}-{% endif %}</td>
            <td>{% if avtomat.security %}{{ avtomat.security }}{% else %}-{% endif %}</td>
            <td>{% if avtomat.competitors %}Есть{% else %}Нет{% endif %}</td>
        </tr>
    {% endfor %}
    </tbody>
    </table>

    {% if request.GET %}
        <script>alert('Автомат {{ request.GET.number }} не добавлен на карту!\nПроверьте корректность адреса.')</script>
    {% endif %}

{% endblock %}

templates/avtomat/avtomat_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block title %}Редактировать автомат{% endblock %}

{% block content %}

    <a href="{% url 'avtomat' %}" class="btn btn-default"><span class="glyphicon glyphicon-share-alt"></span>  Назад</a>

    <div class="row">
        <div class="col-md-offset-4 col-lg-offset-4 col-md-4 col-lg-4">
            <h3>Редактировать автомат: <span class="text-primary">{{ avtomat }}</span><br><small> Серийный номер: {{ avtomat.number }}</small></h3>
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                {% endbuttons %}
            </form>
        </div>
    </div>

    <script>
    function disableStreet() {
        if ($('#id_city').val() == '')
            $('#id_street_label').prop('disabled', true);
        else
            $('#id_street_label').prop('disabled', false);
    }
    $(document).ready(disableStreet);
    $('#id_city').change(disableStreet);
    $('#id_street').hide();
    </script>

    <script src="{% static 'vodomat/js/autocomplete_street.js' %}"></script>

{% endblock %}

templates/avtomat/city.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}Список городов{% endblock %}

{% block content %}

    <ul class="nav nav-tabs">
        <li role="presentation"><a href="{% url 'avtomat' %}">Автоматы</a></li>
        <li role="presentation"><a href="{% url 'route' %}">Маршруты</a></li>
        <li role="presentation"><a href="{% url 'street' %}">Улицы</a></li>
        <li role="presentation" class="active"><a href="{% url 'city' %}">Города</a></li>
    </ul>

    <h3>Список городов <a href="{% url 'city_create' %}" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-plus"></span> Добавить город</a></h3></h3>

    <table class="table">
    <thead>
        <tr class="info">
            <th></th>
            <th>Город</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    {% for city in city_table %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ city }}</td>
            <td><a href="{% url 'city_edit' city.id %}">Редактировать</a></td>
        </tr>
    {% endfor %}
    </tbody>
    </table>

{% endblock %}

templates/avtomat/city_create.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}Добавить город{% endblock %}

{% block content %}

    <a href="{% url 'city' %}" class="btn btn-default"><span class="glyphicon glyphicon-share-alt"></span>  Назад</a>

    <div class="row">
        <div class="col-md-offset-4 col-md-4">
            <h3>Добавить город</h3>
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                {% endbuttons %}
            </form>
        </div>
    </div>

{% endblock %}

templates/avtomat/city_edit.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}Редактировать город{% endblock %}

{% block content %}

    <a href="{% url 'city' %}" class="btn btn-default"><span class="glyphicon glyphicon-share-alt"></span>  Назад</a>

    <div class="row">
        <div class="col-md-offset-4 col-md-4">
            <h3>Редактировать город {{ city }}</h3>
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                {% endbuttons %}
            </form>
        </div>
    </div>

{% endblock %}

templates/avtomat/street.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}Список улиц{% endblock %}

{% block content %}

    <ul class="nav nav-tabs">
        <li role="presentation"><a href="{% url 'avtomat' %}">Автоматы</a></li>
        <li role="presentation"><a href="{% url 'route' %}">Маршруты</a></li>
        <li role="presentation" class="active"><a href="{% url 'street' %}">Улицы</a></li>
        <li role="presentation"><a href="{% url 'city' %}">Города</a></li>
    </ul>

    <h3>Список улиц <a href="{% url 'street_create' %}" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-plus"></span> Добавить улицу</a></h3>

    <table class="table">
    <thead>
        <tr class="info">
            <th></th>
            <th>Город</th>
            <th>Улица</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    {% for street in street_table %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{ street.city }}</td>
            <td>{{ street }}</td>
            <td><a href="{% url 'street_edit' street.id %}">Редактировать</a></td>
        </tr>
    {% endfor %}
    </tbody>
    </table>

{% endblock %}




    <div class="row">
        <div class="col-md-4 col-lg-4">
            <form action="" method="post">
                <div class="input-group">
                    <input type="text" class="form-control" placeholder="Добавить улицу">
                    <span class="input-group-btn">
                        <button class="btn btn-primary">Добавить</button>
                    </span>
                </div>
            </form>
        </div>
    </div>

templates/avtomat/street_create.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}Добавить улицу{% endblock %}

{% block content %}

    <a href="{% url 'street' %}" class="btn btn-default"><span class="glyphicon glyphicon-share-alt"></span>  Назад</a>

    <div class="row">
        <div class="col-md-offset-4 col-md-4">
            <h3>Добавить улицу</h3>
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                {% endbuttons %}
            </form>
        </div>
    </div>

{% endblock %}

templates/avtomat/street_edit.html
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block title %}Редактировать улицу{% endblock %}

{% block content %}

    <a href="{% url 'street' %}" class="btn btn-default"><span class="glyphicon glyphicon-share-alt"></span>  Назад</a>

    <div class="row">
        <div class="col-md-offset-4 col-md-4">
            <h3>Редактировать улицу {{ street }}</h3>
            <form action="" method="post">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                    <button type="submit" class="btn btn-primary">Сохранить</button>
                {% endbuttons %}
            </form>
        </div>
    </div>

{% endblock %}