route/urls.py
from django.conf.urls import url
from .views import RouteView, RouteCreateView, RouteEditView, route_delete_view


urlpatterns = [
    url(r'^$', RouteView.as_view(), name='route'),
    url(r'^create/$', RouteCreateView.as_view(), name='route_create'),
    url(r'^edit/(?P<pk>\d+)/$', RouteEditView.as_view(), name='route_edit'),
    url(r'^delete/(?P<pk>\d+)', route_delete_view, name='route_delete'),
]

status/urls.py
from django.conf.urls import url
from .views import StatusView, StatusAlphabetView, status_detail_view, status_map_view, status_search_form


urlpatterns = [
    url(r'^$', StatusView.as_view(), name='status'),
    url(r'^(\w)/$', StatusAlphabetView.as_view(), name='status_alphabet'),
    url(r'^status_detail/(?P<id>\d+)/$', status_detail_view, name='status_detail'),
    url(r'^search_status_form/$', status_search_form, name='status_search_form'),
    url(r'^map/$', status_map_view, name='status_map'),
]

status/models.py
# coding=utf-8
from __future__ import unicode_literals
from django.db import models
from avtomat.models import Avtomat


class Status(models.Model):
    avtomat = models.ForeignKey(Avtomat, verbose_name='Автомат')
    time = models.DateTimeField(verbose_name='Время')
    water_balance = models.FloatField(verbose_name='Остаток воды в автомате')
    how_money = models.FloatField(verbose_name='Принятая сумма')
    grn = models.IntegerField(default=0, verbose_name='Грн')
    kop = models.IntegerField(default=0, verbose_name='Коп')
    water_price = models.FloatField(verbose_name='Цена за один литр')
    ev_water = models.BooleanField(verbose_name='Наличие воды')
    ev_bill = models.BooleanField(verbose_name='Купюроприемник')
    ev_bill_time = models.IntegerField(default=0, verbose_name='Купюроприемник время')
    ev_coin_time = models.IntegerField(default=0, verbose_name='Монетоприемник время')
    ev_volt = models.BooleanField(verbose_name='Электросеть')
    ev_counter_water = models.BooleanField(verbose_name='Счетчик воды')
    ev_register = models.BooleanField(default=0, verbose_name='Регистратор')
    time_to_block = models.IntegerField(default=99, verbose_name='Время до блокировки')

    def __unicode__(self):
        return '%s' % self.avtomat

    class Meta:
        ordering = ('-time', )
        db_table = 'status'
        verbose_name = 'Статус'
        verbose_name_plural = 'Статуc'

status/forms.py
# coding=utf-8
from avtomat.models import Avtomat
from django import forms


class UIWidget(forms.Form):
    class Media:
        css = {'all': ('//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css', )}
        js = ('https://code.jquery.com/ui/1.12.1/jquery-ui.js', )


class StatusSearchForm(UIWidget):
    avtomat_label = forms.CharField(widget=forms.TextInput(attrs={'autofocus': 1, 'class': 'form-control', 'placeholder': u'Ввелите адрес автомата'}), label='')
    id = forms.IntegerField(widget=forms.HiddenInput(attrs={'class': 'form-control'}))

    def clean_id(self):
        data = self.cleaned_data['id']
        if not data:
            raise forms.ValidationError('Неверный ввод')
        else:
            return data

status/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
import pygal
from pygal.style import Style
import datetime
from .models import Status
from avtomat.models import Avtomat
from collection.models import Collection
from statistic.models import Statistic
from route.models import Route


class StatusView(LoginRequiredMixin, ListView):
    queryset = Status.objects.all()
    template_name = 'status/status.html'
    context_object_name = 'status_table'

    def get_context_data(self, **kwargs):
        context = super(StatusView, self).get_context_data(**kwargs)
        context['routes'] = Route.objects.all()
        context['status_count'] = Status.objects.count()
        return context

    def get_queryset(self):
        route = self.request.GET.get('route')
        if route:
            return Status.objects.filter(avtomat__route__route_number=route).order_by('avtomat')
        else:
            return Status.objects.all().select_related('avtomat__street', 'avtomat__street__city')


@login_required
def status_search_form(request):
    avtomat_id = request.POST.get('id')
    if avtomat_id:
        return redirect('status_detail', id=avtomat_id)
    else:
        return redirect('status')


class StatusAlphabetView(LoginRequiredMixin, ListView):
    template_name = 'status/status.html'
    context_object_name = 'status_table'

    def get_queryset(self):
        return Status.objects.filter(avtomat__street__street__istartswith=self.args[0]).select_related('avtomat__street', 'avtomat__street__city')


@login_required
def status_detail_view(request, id):
    today = datetime.date.today()
    one_day_ago = today - datetime.timedelta(days=1)
    two_days_ago = today - datetime.timedelta(days=2)
    avtomat = Avtomat.objects.get(id=id)
    status = Status.objects.get(avtomat=id)
    collections = Collection.objects.filter(avtomat=id, time__date=today)
    statistic = Statistic.objects.filter(avtomat=id, time__gte=today).values_list('water_balance', flat=True)
    custom_style_water = Style(colors=('#79aec8',), font_family='Roboto')
    hist_water = pygal.Line(height=300, show_y_guides=False, show_legend=False, margin=0, style=custom_style_water,
                            dots_size=1)
    hist_water.add('Water', statistic.reverse())
    if avtomat.size:
        balance = int(status.water_balance / avtomat.size * 100)
    else:
        balance = 0
    return render(request, 'status/status_detail.html', {'avtomat': avtomat, 'status': status, 'today': today,
                                                         'one_day_ago': one_day_ago,
                                                         'two_days_ago': two_days_ago,
                                                         'collections': collections,
                                                         'hist_water': hist_water.render_data_uri(),
                                                         'balance': balance})


@login_required
def status_map_view(request):
    status = Status.objects.all().select_related('avtomat__street', 'avtomat__street__city')
    return render(request, 'status/map_google.html', {'status': status})

templates/status/map_google.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load l10n %}

{% block title %}Карта автоматов Google{% endblock %}
{% block meta %}<meta http-equiv="refresh" content="1200">{% endblock %}

{% block content %}

    <ul class="nav nav-tabs">
        <li role="presentation"><a href="{% url 'status' %}">Статус автоматов</a></li>
        <li role="presentation" class="active"><a href="{% url 'status_map' %}">Карта автоматов</a></li>
{#        <li role="presentation"><a href="{% url 'street' %}">Улицы</a></li>#}
{#        <li role="presentation"><a href="{% url 'city' %}">Города</a></li>#}
    </ul>
{#    <br>#}

    <h3>Карта расположения автоматов</h3>
    <div id="map"></div>

    <script type="text/javascript">
        function initMap() {
            var kharkov = {lat: 49.99, lng: 36.23};
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 11,
                center: kharkov
            });
            {% for avtomat in status %}
            {% if avtomat.avtomat.latitude and avtomat.avtomat.longitude %}
                    var point = new google.maps.LatLng({{ avtomat.avtomat.latitude|unlocalize }},{{ avtomat.avtomat.longitude|unlocalize }});
                    var marker = new google.maps.Marker({
                        position: point,
                        title: "{{ avtomat }}",
                        label: "{{ avtomat.water_balance }}",
                        map: map
                    });
            {% endif %}
            {% endfor %}
        }
    </script>

    <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB3wwrPtsRIyV2twvjKvHAwE-Q3aNx5Yjs&callback=initMap">
    </script>

{% endblock %}





AIzaSyB3wwrPtsRIyV2twvjKvHAwE-Q3aNx5Yjs

templates/status/map_yandex.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load l10n %}

{% block title %}Карта автоматов Yandex{% endblock %}
{% block meta %}<meta http-equiv="refresh" content="1200">{% endblock %}

{% block content %}

    <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>

    <script type="text/javascript">
        ymaps.ready(init);

        function init(){
            var myMap = new ymaps.Map("map", {
                center: [49.99, 36.23],
                zoom: 12
            });
            {% for avtomat in status %}
                {% if avtomat.avtomat.latitude and avtomat.avtomat.longitude %}
                    var myPlacemark = new ymaps.Placemark([{{ avtomat.avtomat.latitude|unlocalize }}, {{ avtomat.avtomat.longitude|unlocalize }}],
                       {
                        hintContent: '{{ avtomat.avtomat }}',
                        balloonContent: 'Остаток воды<br>{{ avtomat.water_balance }}(л)'
                       },
                        {
                         preset:{% if avtomat.water_balance < 100 %}'islands#redCircleIcon'{% else %}'islands#blueCircleIcon'{% endif %}
                        });
                    myMap.geoObjects.add(myPlacemark);
                {% endif %}
            {% endfor %}
        }
    </script>

    <h3>Карта расположения автоматов</h3>
    <div id="map"></div>

{% endblock %}

templates/status/status.html
{% extends 'base.html' %}
{% load extras %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block title %}Статус автоматов{% endblock %}
{% block meta %}<meta http-equiv="refresh" content="300">{% endblock %}
{% block css %}
    <link rel="stylesheet" href='//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css'>
{% endblock %}

{% block content %}

    <ul class="nav nav-tabs">
        <li role="presentation" class="active"><a href="{% url 'status' %}">Статус автоматов</a></li>
        <li role="presentation"><a href="{% url 'status_map' %}">Карта автоматов</a></li>
    </ul>
    <br>

    {% block alphabet %}
        {% include 'alphabet.html' %}
    {% endblock %}

    <br>
    <div class="row well well-sm">
        <div class="col-lg-8">
            <div class="input-group">
                <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Выбрать маршрут <span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    {% for i in routes %}
                        <li><a href="?route={{ i }}">{{ i }} ({{ i.driver1 }}/{{ i.driver2 }})</a></li>
                    {% endfor %}
                        <li><a href="?">Все</a></li>
                </ul>
            </div>
        </div>

        <div class="col-lg-4">
            <form action="{% url 'status_search_form' %}" method="post">
                {% csrf_token %}
                <div class="input-group">
                    <input type="text" class="form-control" name="avtomat_label" id="id_avtomat_label" placeholder="Введите адрес автомата" autofocus="1">
                    <input type="hidden"name="id" id="id_id">
                    <span class="input-group-btn">
                        <button class="btn btn-primary" type="submit">Поиск</button>
                    </span>
                </div>
            </form>
        </div>
        <!--<form action="" method="post">-->
            <!--{% csrf_token %}-->
            <!--<div class="col-lg-5">-->
                <!--<div class="input-group">-->
                    <!--<label class="checkbox-inline">-->
                        <!--<input type="checkbox" name="ev_water" value="1">Вода-->
                    <!--</label>-->
                    <!--<label class="checkbox-inline">-->
                        <!--<input type="checkbox" name="ev_volt" value="1">Сеть-->
                    <!--</label>-->
                    <!--<label class="checkbox-inline">-->
                        <!--<input type="checkbox" name="ev_counter" value="1">Счетчик-->
                    <!--</label>-->
                    <!--<label class="checkbox-inline">-->
                        <!--<input type="checkbox" name="ev_register" value="1">Регистратор-->
                    <!--</label>-->
                    <!--<label class="checkbox-inline">-->
                        <!--<input type="checkbox" name="ev_bill" value="1">Купюрник-->
                    <!--</label>-->
                    <!--<button class="btn btn-primary" type="submit" style="margin-left: 5px">Сортировать</button>-->
                <!--</div>-->
            <!--</div>-->
        <!--</form>-->
    </div>

    <h4>Статус автоматов {% now 'DATE_FORMAT' %}
        {% if request.GET.route %}(Маршрут: {{ request.GET.route }}){% endif %}
        <span class="label label-info">{{ status_count }}</span>
    </h4>

    <h3>{% if error %}{{error}}{% endif %}</h3>

    <table class="table tablesorter">
    <thead>
        <tr class="info">
            <th>Номер</th>
            <th>Адрес</th>
            <th>Время</th>
            <th>Остаток</th>
            <th>Сумма</th>
            <th>Грн</th>
            <th>Коп</th>
            <th>Цена</th>
            <th>Вода</th>
            <th>Сеть</th>
            <th>Сч-к</th>
            <th>Ре-р</th>
            <th>Куп1</th>
            <th>Куп2</th>
            <th>Мон1</th>
            <th>Блок</th>
            <th>Конк</th>
        </tr>
    </thead>
    <tbody>
    {% for avtomat in status_table %}
        <tr onclick="document.location='{% url 'status_detail' avtomat.avtomat.id %}'" onmouseover="this.className='active'" onmouseout="this.className=''">
           <td>{{ avtomat.avtomat.number }}</td>
           <td {% if avtomat.ev_water == 1 or avtomat.ev_volt == 1 or avtomat.ev_bill == 1 or avtomat.ev_counter_water == 1 or avtomat.ev_register == 1 %} bgcolor='#faebd7' {% else %} bgcolor="#c4dce8" {% endif %}>
               {{ avtomat }}
           </td>
           <td>{{ avtomat.time|date:"d M H:i" }}</td>
           <td>{{ avtomat.water_balance }}</td>
           <td>{{ avtomat.how_money }}</td>
           <td>{{ avtomat.grn }}</td>
           <td>{{ avtomat.kop }}</td>
           <td>{{ avtomat.water_price }}</td>
           <td>{% if avtomat.ev_water %}<span class="text-danger">Сбой</span>{% else %}Норма{% endif %}</td>
           <td>{% if avtomat.ev_volt %}<span class="text-danger">Сбой</span>{% else %}Норма{% endif %}</td>
           <td>{% if avtomat.ev_counter_water %}<span class="text-danger">Сбой</span>{% else %}Норма{% endif %}</td>
           <td>{% if avtomat.ev_register %}<span class="text-danger">Сбой</span>{% else %}Норма{% endif %}</td>
           <td>{% if avtomat.ev_bill %}<span class="text-danger">Сбой</span>{% else %}Норма{% endif %}</td>
           <td>{{ avtomat.ev_bill_time }}</td>
           <td>{{ avtomat.ev_coin_time }}</td>
           <td>{{ avtomat.time_to_block }}</td>
           <td>{% if avtomat.avtomat.competitors %}<span class="text-success">Есть</span>{% else %}Нет{% endif %}</td>
        </tr>
    {% endfor %}
    </tbody>
    </table>

    <script src='https://code.jquery.com/ui/1.12.1/jquery-ui.js'></script>
    <script src="{% static 'vodomat/js/autocomplete_avtomat.js' %}"></script>

{% endblock %}

templates/status/status_detail.html
{% extends 'base.html' %}

{% block title %}{{ avtomat }}{% endblock %}

{% block content %}
    <h3>{{ avtomat }}</h3>
    <p>Просмотреть статистику за
        <a href="{% url 'statistic' today|date:'dmY' today|date:'dmY' avtomat.id %}" target="_blank" type="button" class="btn btn-info">1</a>
        <a href="{% url 'statistic' one_day_ago|date:'dmY' today|date:'dmY' avtomat.id %}" target="_blank" type="button" class="btn btn-info">2</a>
        <a href="{% url 'statistic' two_days_ago|date:'dmY' today|date:'dmY' avtomat.id %}" target="_blank" type="button" class="btn btn-info">3</a>
        дня
    </p>
    <div class="row">

        <div class="col-md-9">
            <div class="panel panel-info">
            <div class="panel-heading">Статус {{ status.time }}</div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Вода</th>
                            <th>Сеть</th>
                            <th>Куп1</th>
                            <th>Сч-к</th>
                            <th>Ре-р</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>{% if status.ev_water %}<span class="text-danger">Сбой</span>{% else %}Норма{% endif %}</td>
                            <td>{% if status.ev_volt %}<span class="text-danger">Сбой</span>{% else %}Норма{% endif %}</td>
                            <td>{% if status.ev_bill %}<span class="text-danger">Сбой</span>{% else %}Норма{% endif %}</td>
                            <td>{% if status.ev_counter_water %}<span class="text-danger">Сбой</span>{% else %}Норма{% endif %}</td>
                            <td>{% if status.ev_register %}<span class="text-danger">Сбой</span>{% else %}Норма{% endif %}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>

        <div class="col-md-3">
            <div class="panel panel-info">
            <div class="panel-heading">Инкассации {{ today }}</div>
                <table class="table">
                    <thead>
                        <tr>
                            <th>Время</th>
                            <th>Сумма</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for collection in collections %}
                            <tr>
                                <td>{{ collection.time|date:'H:i' }}</td>
                                <td>{{ collection.how_money }}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>

        <div class="col-md-9">
            <div class="panel panel-info">
            <div class="panel-heading">График реализации {{ today }}</div>
                <embed type="image/svg+xml" src= {{ hist_water|safe }} ></embed>
            </div>
        </div>

        <div class="col-md-3">
            <div class="panel panel-info">
            <div class="panel-heading">{{ avtomat }}</div>
                <ul class="list-group">
                    <li class="list-group-item">Остаток(дм&#179): {{ status.water_balance }}</li>
                    <li class="list-group-item">Сумма(грн): {{ status.how_money }}</li>
                    <li class="list-group-item">Грн: {{ status.grn }}</li>
                    <li class="list-group-item">Коп: {{ status.kop }}</li>
                    <li class="list-group-item">Цена(грн): {{ status.water_price }}</li>
                    <li class="list-group-item">Купюрник(мин): {{ status.ev_bill_time }}</li>
                    <li class="list-group-item">Монетник(мин): {{ status.ev_coin_time }}</li>
                    <li class="list-group-item">Блокировка(ч): {{ status.time_to_block }}</li>
                </ul>
            </div>
        </div>

        <div class="col-md-3">
            <h4>Остаток воды</h4>
            <div class="progress">
                <div class="progress-bar {% if balance < 10 %}progress-bar-danger{% endif %}" aria-valuemin="0" aria-valuemax="100" style="width: {{ balance }}%;">{{ balance }}%</div>
            </div>
        </div>

    </div>
{% endblock %}